package com.keylock.decryptor

import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test

/**
 * Known-answer test (KAT). These values MUST stay byte-for-byte in sync with
 * /test-vectors.json (generated by desktop/scripts/generate-test-vectors.cjs)
 * — this is the cross-language check that Node's crypto.pbkdf2Sync and this
 * module's hand-rolled Pbkdf2HmacSha256 agree on every byte. If you
 * regenerate test-vectors.json, update these constants to match.
 *
 * Runs on the plain JVM via `./gradlew test` — no device/emulator/Robolectric
 * needed, since decryptWithFingerprint() never touches the Android framework.
 */
class KeyLockDecryptorTest {

    private val fingerprint = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
    private val saltBase64 = "oKGio6SlpqeoqaqrrK2urw=="
    private val ivBase64 = "sLGys7S1tre4ubq7"
    private val plaintext = "KeyLock-KAT-vector-secret-value-2026"
    private val expectedEncryptedKeyBase64 = "iE1RmzDPdRRIa5q+cO5utX7D3YRTvKMEwW+JFnv/zEsB+9WupcVxpUx+j1IqdsM6Ijoszg=="

    @Test
    fun `decrypts the committed known-answer vector to its known plaintext`() {
        val result = KeyLockDecryptor.decryptWithFingerprint(
            fingerprint,
            ivBase64,
            saltBase64,
            expectedEncryptedKeyBase64
        )
        assertEquals(plaintext, result)
    }

    @Test
    fun `pbkdf2 derives the same key material Node's pbkdf2Sync would (implicit via KAT)`() {
        // The KAT above only passes if PBKDF2 + AES-GCM together reproduce ciphertext
        // generated by desktop/electron/crypto.ts. A drift in either would fail it.
        val key = Pbkdf2HmacSha256.derive(
            password = hexToBytesForTest(fingerprint),
            salt = java.util.Base64.getDecoder().decode(saltBase64),
            iterations = 100_000,
            keyLengthBytes = 32
        )
        assertEquals(32, key.size)
    }

    @Test
    fun `throws SigningCertificateMismatchException for the wrong fingerprint`() {
        val wrongFingerprint = "f".repeat(64)
        assertThrows(SigningCertificateMismatchException::class.java) {
            KeyLockDecryptor.decryptWithFingerprint(wrongFingerprint, ivBase64, saltBase64, expectedEncryptedKeyBase64)
        }
    }

    @Test
    fun `throws SigningCertificateMismatchException for a tampered ciphertext`() {
        val tamperedBytes = java.util.Base64.getDecoder().decode(expectedEncryptedKeyBase64)
        tamperedBytes[0] = (tamperedBytes[0].toInt() xor 0xFF).toByte()
        val tamperedBase64 = java.util.Base64.getEncoder().encodeToString(tamperedBytes)
        assertThrows(SigningCertificateMismatchException::class.java) {
            KeyLockDecryptor.decryptWithFingerprint(fingerprint, ivBase64, saltBase64, tamperedBase64)
        }
    }

    @Test
    fun `throws MalformedPayloadException for a malformed fingerprint`() {
        assertThrows(MalformedPayloadException::class.java) {
            KeyLockDecryptor.decryptWithFingerprint("not-a-fingerprint", ivBase64, saltBase64, expectedEncryptedKeyBase64)
        }
    }

    @Test
    fun `throws MalformedPayloadException for a wrong-length IV`() {
        val shortIvBase64 = java.util.Base64.getEncoder().encodeToString(ByteArray(4))
        assertThrows(MalformedPayloadException::class.java) {
            KeyLockDecryptor.decryptWithFingerprint(fingerprint, shortIvBase64, saltBase64, expectedEncryptedKeyBase64)
        }
    }

    @Test
    fun `round-trips a fresh secret encrypted with the same primitives`() {
        // Encrypts inline (test-only) with the same PBKDF2 + AES-GCM primitives the
        // decryptor uses, to check the decrypt path independent of the fixed KAT bytes.
        val secret = "sk-live-example-not-real-1234567890"
        val salt = ByteArray(16) { (it + 1).toByte() }
        val iv = ByteArray(12) { (it + 50).toByte() }
        val certBytes = hexToBytesForTest(fingerprint)
        val key = Pbkdf2HmacSha256.derive(certBytes, salt, 100_000, 32)

        val cipher = javax.crypto.Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(
            javax.crypto.Cipher.ENCRYPT_MODE,
            javax.crypto.spec.SecretKeySpec(key, "AES"),
            javax.crypto.spec.GCMParameterSpec(128, iv)
        )
        val encryptedKey = cipher.doFinal(secret.toByteArray(Charsets.UTF_8))

        val result = KeyLockDecryptor.decryptWithFingerprint(
            fingerprint,
            java.util.Base64.getEncoder().encodeToString(iv),
            java.util.Base64.getEncoder().encodeToString(salt),
            java.util.Base64.getEncoder().encodeToString(encryptedKey)
        )
        assertEquals(secret, result)
    }

    private fun hexToBytesForTest(hex: String): ByteArray {
        val bytes = ByteArray(hex.length / 2)
        for (i in bytes.indices) {
            bytes[i] = ((Character.digit(hex[i * 2], 16) shl 4) + Character.digit(hex[i * 2 + 1], 16)).toByte()
        }
        return bytes
    }
}
