import { KnownAnswerVector } from "./crypto";

/**
 * Keep in sync with /test-vectors.json (generated by
 * desktop/scripts/generate-test-vectors.cjs). Hardcoded here so the
 * in-app self-test works from a packaged build without relying on a
 * relative path to the repo root.
 */
export const KNOWN_ANSWER_VECTOR: KnownAnswerVector = {
  fingerprint: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
  saltBase64: "oKGio6SlpqeoqaqrrK2urw==",
  ivBase64: "sLGys7S1tre4ubq7",
  plaintext: "KeyLock-KAT-vector-secret-value-2026",
  expectedEncryptedKeyBase64: "iE1RmzDPdRRIa5q+cO5utX7D3YRTvKMEwW+JFnv/zEsB+9WupcVxpUx+j1IqdsM6Ijoszg==",
};
